---
name: Build PostgreSQL images

on:
  schedule:
    - cron: "2 2 * * SUN"
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: camptocamp/initialise-gopass-summon-action@v2
      with:
        ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
        github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
        patterns: docker

    - name: "Build and Push images"
      env:
        PUSH_DOCKER_HUB: true
        PUSH_GHCR: true
      run: |
        make all
